Feature
MayPyone/Budget pull request #1
Opened 2024-02-09 11:05 UTC by MayPyone

Splash screen

- A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
- Sign up and log in pages

> The user should be able to register in the app with full name, email and password (all mandatory).
> The user can log into the app using email and password.
> If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

Home page (categories page)

- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

Transactions page

- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

"Add a new category" page

- The user fills out a form to create a new category, indicating their name and icon (both mandatory).
- The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

"Add a new transaction" page

- The user fills out a form to create a new transaction with:
- name (mandatory)
- amount (mandatory)
- categories (mandatory at least one)
- The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

2024-02-09 14:13 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @MayPyone,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-09 14:13 UTC, omar-muhamad commented on README.md
> +
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=the%20project%20features.-,you%20should%20also%20highlight%20some%20interesting%20piece%20of%20code%20or%20something%20you%20built%20that%20you%20are%20very%20proud%20of.,-For%20recording%20the), Please record a new video and don't forget to highlight some interesting piece of code or something you built that you are very proud of.

2024-02-09 14:13 UTC, omar-muhamad commented on db/migrate/20240206144205_create_entities.rb
> +end
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=You%20need%20to%20change%20the%20%22Entity%22%20name%20according%20to%20the%20theme%20you%20have%20chosen%20for%20your%20project), You need to change the "Entity" name according to the theme you have chosen for your project. Please fix that.
[Hint] You can name your table `payments` instead of `entities`, Also don't forget to change the model, controller, views, and routes names too.

- [ ] As per the given ERD diagram, You have a many-to-many relationship between the `Group` and `Entity`(Payment) tables, so please create a join table between them and you can call it `Group_Payments`. 
[Hint] Don't forget to set up the associations between models in the correct way after this change.

2024-02-09 14:13 UTC, omar-muhamad commented on app/views/groups/index.html.erb
> +      <div><%= "$" "#{group.total_amount}" %></div>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=When%20the%20user%20clicks%20(or%20taps)%20on%20a%20category%20item%2C%20the%20application%20navigates%20to%20the%20transactions%20page%20for%20that%20category.), Please make this link navigates to the transactions page for that category which is `group_entities_path` (`group_payments_path` after the change I asked above), not `group_path` as you did here.

2024-02-09 14:13 UTC, Omar-Muhamad commented on app/views/entities/index.html.erb
> +</div>
- [ ] As per the project [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=a%20new%20category.-,Transactions%20page,-For%20a%20given) This should be your transaction page, so please copy the changes you made inside `groups#index` view and paste it here.

2024-02-09 14:13 UTC, Omar-Muhamad commented on spec/models/entity_spec.rb
> +    end
- [ ] Good job adding models and controller specs, As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Testing%20requirements-,Create%20unit%20and%20integration%20tests%20for%20all%20the%20most%20important%20components%20of%20your%20RoR%20application.,-Technical%20requirements), Please add integration specs for all the most important components of your RoR application too.

2024-02-09 14:23 UTC, Omar-Muhamad commented on app/views/splash/index.html.erb
> +    </div>
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=Colors.-,Typography%3A%20font%20face%2C%20size%20and%20weight.,-Layout%3A%20composition%20and), Please add the correct font families for all elements of all pages in your app which is `proxima nova` light and bold.

![image](https://github.com/MayPyone/Budget/assets/68796232/a1ed2971-6614-4c14-8121-53db14f8b62a)

2024-02-09 14:23 UTC, Omar-Muhamad commented on README.md
> +
- [ ] The license link in the README file is broken, Please provide a valid link.

![image](https://github.com/MayPyone/Budget/assets/68796232/62ec8cf5-b934-4e5c-8829-8aa2107b7fe2)

2024-02-09 17:01 UTC, shahadat3669 requested changes
Hi @MayPyone, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ Updated Readme file
✅ implemented a more meaningful naming convention.
✅ All test cases passed


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadat3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-02-09 17:01 UTC, shahadat3669 commented on README.md
> +- [Video Link](https://www.loom.com/share/d467834ce70342349321fc1ef5eeb2ac?sid=9af5e4d7-67d7-4edc-9c4f-cd3e423a4b31)
🎬 Great job on your project! To enhance your submission, consider the following suggestion:

- [ ] **Record a New Video:** As part of the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#:~:text=the%20project%20features.-,you%20should%20also%20highlight%20some%20interesting%20piece%20of%20code%20or%20something%20you%20built%20that%20you%20are%20very%20proud%20of.,-For%20recording%20the), you are encouraged to record a video which also highlights some interesting piece of code or a specific feature you built that you are proud of. The video is an excellent opportunity to showcase your work visually and provide insights into the project. Please create a new video that includes this highlight and make sure to visually demonstrate the mentioned code or feature.

Recording a video can add an engaging dimension to your project presentation and allow you to share your enthusiasm about specific aspects of your work. Keep up the good work! 🚀🎥

2024-02-09 17:01 UTC, shahadat3669 commented on README.md
> +- [Live Demo Link](https://mybudget-shzp.onrender.com)
- [ ] 🚀 Good progress on your project! However, to ensure that the latest updates and improvements are reflected in the live version, I recommend redeploying your application. This will allow users and reviewers to access the most recent version of your code, incorporating the changes you made after the previous review.

By ensuring that the live version is updated, you provide an accurate representation of your work for both users and reviewers. If you encounter any issues during the redeployment, feel free to ask for assistance. Keep up the excellent work! 🌐👩‍💻

2024-02-09 17:01 UTC, shahadat3669 commented on app/views/groups/index.html.erb
👍 Great progress on your project! To further enhance the quality and reliability of your codebase, consider the following suggestion which also mentioned by the previous reviewer:

- [ ] **Integration Testing:** As you've successfully implemented integration testing in your "Blog Post" project using RSpec and Capybara, it's recommended to follow a similar approach for this project. Integration tests provide a comprehensive way to ensure that different parts of your application work together as expected. Create integration tests that cover critical user flows, interactions, and features. This will help catch potential issues and ensure the smooth functioning of your application.

   If you encounter any challenges or need assistance with integration testing, feel free to reach out for guidance. Integrating tests for various scenarios will contribute to the overall robustness of your application.

Keep up the good work! 🚀🛠️

2024-02-10 11:06 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @MayPyone,

#### Nice job making the required changes. Unfortunately, you missed some of them but you are almost there.

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-10 11:06 UTC, omar-muhamad commented on README.md
> +- [Video Link](https://www.loom.com/share/d467834ce70342349321fc1ef5eeb2ac?sid=9af5e4d7-67d7-4edc-9c4f-cd3e423a4b31)
- [ ] The video demo link is broken, as I requested and the last reviewer requested, Please record a new presentation video, put the new link in the README file, and don't forget to fulfill these requirements in it:

![image](https://github.com/MayPyone/Budget/assets/68796232/f471dcdc-545f-4de6-aa5e-0179a05aa790)

![image](https://github.com/MayPyone/Budget/assets/68796232/c7e8eccc-9ad3-41f5-828a-920b9eaa1df0)

2024-02-10 12:05 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @MayPyone,

#### Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### Congratulations! 🎉 

![giphy (1)](https://user-images.githubusercontent.com/68796232/223283296-e4ee61b3-5609-4707-a1c7-5a3da02d5db9.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2024-02-18 08:07 UTC, merged